# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-17 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=32, unique=True)),
                ('usex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('upwd', models.CharField(max_length=128)),
                ('uemail', models.EmailField(max_length=254, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('uphone', models.CharField(max_length=11)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
    ]
